# Generated by Django 5.2.2 on 2025-08-20 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='threads',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='logoimage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='yearsofexperience',
        ),
    ]
